"""Unitree G1 with a Livox Mid-360 and a D435 camera, ready to drop into a scene.

Import the configs and add them to any ``InteractiveSceneCfg``:

    from g1_sim.robots.unitree_g1_lidar import G1_LIDAR_CFG, mid360_cfg, camera_cfg

    @configclass
    class MySceneCfg(InteractiveSceneCfg):
        robot  = G1_LIDAR_CFG.replace(prim_path="{ENV_REGEX_NS}/Robot")
        lidar  = mid360_cfg("{ENV_REGEX_NS}/Robot")
        camera = camera_cfg("{ENV_REGEX_NS}/Robot")

The USD is generated by ``scripts/convert_g1_urdf_to_usd.py`` and is imported
lazily, so this module can be read without a running simulator.
"""

from __future__ import annotations

import math
from pathlib import Path

import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets import ArticulationCfg
from isaaclab.sensors import CameraCfg, LidarSensorCfg
from isaaclab.sensors.ray_caster.patterns import LivoxPatternCfg
from isaaclab.utils import configclass

G1_USD_PATH = str(Path(__file__).resolve().parents[2] / "assets/g1_29dof_sensors.usd")

# --------------------------------------------------------------------------
# Sensor mounts
#
# Both links already exist in g1_29dof.urdf as fixed children of torso_link;
# the conversion keeps them because merge_fixed_joints is disabled. The values
# below mirror the URDF so sensor offsets and published TF agree.
# --------------------------------------------------------------------------

MID360_PARENT = "torso_link"
# Per Unitree URDF: xyz=(0.0002835, 0.00003, 0.40618), rpy=(0, 0.0401, 0).
MID360_POS = (0.0002835, 0.00003, 0.40618)
# wxyz quaternion for rpy=(0, 0.0401, 0) — ~2.3° pitch about Y-axis, no roll.
import math as _math
_MID360_PITCH = 0.0401
MID360_QUAT = (
    _math.cos(_MID360_PITCH / 2),  # w
    0.0,                            # x (roll=0)
    _math.sin(_MID360_PITCH / 2),  # y (pitch)
    0.0,                            # z (yaw=0)
)

D435_PARENT = "torso_link"
D435_POS = (0.0576235, 0.01753, 0.41987)
# rpy = (0, 0.8307767, 0): pitched ~47.6 deg downward, so the camera covers the
# near ground that the LiDAR's -7.2 deg floor cannot reach.
_D435_PITCH = 0.8307767239493009
D435_QUAT = (math.cos(_D435_PITCH / 2), 0.0, math.sin(_D435_PITCH / 2), 0.0)

# Steepest downward ray in the Mid-360 pattern. There is no nadir ray, so the
# sensor is blind within roughly 8x its mount height - see Plan.md.
MID360_MIN_TILT_DEG = 7.16

JOINT_GROUPS = {
    "legs": [".*_hip_pitch_joint", ".*_hip_roll_joint", ".*_hip_yaw_joint", ".*_knee_joint"],
    "feet": [".*_ankle_pitch_joint", ".*_ankle_roll_joint"],
    "waist": ["waist_yaw_joint", "waist_roll_joint", "waist_pitch_joint"],
    "arms": [
        ".*_shoulder_pitch_joint",
        ".*_shoulder_roll_joint",
        ".*_shoulder_yaw_joint",
        ".*_elbow_joint",
        ".*_wrist_roll_joint",
        ".*_wrist_pitch_joint",
        ".*_wrist_yaw_joint",
    ],
}

# A stable, slightly crouched stance: knees and hips bent so the robot settles
# instead of buckling on the first physics step.
DEFAULT_JOINT_POS = {
    ".*_hip_pitch_joint": -0.20,
    ".*_knee_joint": 0.42,
    ".*_ankle_pitch_joint": -0.23,
    ".*_shoulder_pitch_joint": 0.35,
    ".*_elbow_joint": 0.87,
    "left_shoulder_roll_joint": 0.18,
    "right_shoulder_roll_joint": -0.18,
}

# Torso height in the default stance; the base spawns here so the feet start
# just above the ground rather than intersecting it.
DEFAULT_BASE_HEIGHT = 0.74


G1_LIDAR_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path=G1_USD_PATH,
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=8,
            solver_velocity_iteration_count=4,
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, DEFAULT_BASE_HEIGHT),
        joint_pos=DEFAULT_JOINT_POS,
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=0.9,
    actuators={
        # Legs carry the robot's weight and need the stiffest gains; arms are
        # mostly along for the ride and are kept compliant.
        "legs": ImplicitActuatorCfg(
            joint_names_expr=JOINT_GROUPS["legs"],
            effort_limit=300.0,
            velocity_limit=100.0,
            stiffness=150.0,
            damping=5.0,
            armature=0.01,
        ),
        "feet": ImplicitActuatorCfg(
            joint_names_expr=JOINT_GROUPS["feet"],
            effort_limit=50.0,
            velocity_limit=100.0,
            stiffness=20.0,
            damping=2.0,
            armature=0.01,
        ),
        "waist": ImplicitActuatorCfg(
            joint_names_expr=JOINT_GROUPS["waist"],
            effort_limit=200.0,
            velocity_limit=100.0,
            stiffness=200.0,
            damping=5.0,
            armature=0.01,
        ),
        "arms": ImplicitActuatorCfg(
            joint_names_expr=JOINT_GROUPS["arms"],
            effort_limit=100.0,
            velocity_limit=100.0,
            stiffness=40.0,
            damping=10.0,
            armature=0.01,
        ),
    },
)
"""G1 with 29 actuated joints and both sensor mounts preserved."""


def mid360_cfg(
    robot_prim_path: str,
    mesh_prim_paths: list[str] | None = None,
    samples: int = 20000,
    update_frequency: float = 10.0,
    max_distance: float = 40.0,
    debug_vis: bool = False,
) -> LidarSensorCfg:
    """Livox Mid-360 attached to the G1's torso.

    Args:
        robot_prim_path: prim path of the robot, e.g. ``"{ENV_REGEX_NS}/Robot"``.
        mesh_prim_paths: what the rays may hit. Defaults to ``["/World/ground"]``.
        samples: rays per scan. **Do not lower this to save time** - the loader
            takes a contiguous slice of a time-ordered scan trajectory, so a
            smaller value narrows the elevation coverage rather than thinning
            it. Below ~20000 the pattern loses its downward rays entirely and
            the ground becomes invisible. Use the sensor's ``downsample``
            option instead.
        update_frequency: scan rate in Hz; 10 Hz matches the real device.
        max_distance: maximum range in metres.
        debug_vis: draw rays in the viewer.
    """
    if samples < 20000:
        raise ValueError(
            f"samples={samples} is below the Mid-360's native 20000. Because the "
            "scan pattern is sliced in time order, this silently removes all "
            "downward rays. Use downsample to reduce ray count instead."
        )

    return LidarSensorCfg(
        prim_path=f"{robot_prim_path}/{MID360_PARENT}",
        offset=LidarSensorCfg.OffsetCfg(pos=MID360_POS, rot=MID360_QUAT),
        pattern_cfg=LivoxPatternCfg(sensor_type="mid360", samples=samples),
        mesh_prim_paths=mesh_prim_paths if mesh_prim_paths is not None else ["/World/ground"],
        max_distance=max_distance,
        min_range=0.1,
        return_pointcloud=True,
        # Sensor-frame points: TF places them in the world, which keeps the
        # published cloud correct even while the robot moves.
        pointcloud_in_world_frame=False,
        update_frequency=update_frequency,
        debug_vis=debug_vis,
    )


def camera_cfg(
    robot_prim_path: str,
    width: int = 640,
    height: int = 480,
    update_period: float = 0.1,
) -> CameraCfg:
    """RealSense D435-style RGB-D camera on the G1's torso.

    Resolution defaults below the real D435's 1280x720: rendering dominates the
    frame budget on an 8 GB laptop GPU, and detection runs off the LiDAR anyway.
    """
    return CameraCfg(
        prim_path=f"{robot_prim_path}/{D435_PARENT}/d435_camera",
        offset=CameraCfg.OffsetCfg(pos=D435_POS, rot=D435_QUAT, convention="ros"),
        update_period=update_period,
        width=width,
        height=height,
        data_types=["rgb", "distance_to_image_plane"],
        spawn=sim_utils.PinholeCameraCfg(
            # ~69 deg horizontal FOV, matching the D435.
            focal_length=1.93,
            focus_distance=400.0,
            horizontal_aperture=2.682,
            clipping_range=(0.1, 20.0),
        ),
    )


def blind_radius(mount_height: float) -> float:
    """Radius of the Mid-360's blind cone at a given mount height, in metres."""
    return mount_height / math.tan(math.radians(MID360_MIN_TILT_DEG))


@configclass
class G1LidarSceneCfg:
    """Convenience bundle of the three configs for a standard single-robot scene."""

    robot: ArticulationCfg = G1_LIDAR_CFG.replace(prim_path="{ENV_REGEX_NS}/Robot")
    lidar: LidarSensorCfg = mid360_cfg("{ENV_REGEX_NS}/Robot")
    camera: CameraCfg = camera_cfg("{ENV_REGEX_NS}/Robot")
